/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OpencodeRouteImport } from './routes/opencode'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as CodexRouteImport } from './routes/codex'
import { Route as ClaudeCodeRouteImport } from './routes/claude-code'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as DocsWorktreesRouteImport } from './routes/docs/worktrees'
import { Route as DocsVoiceRouteImport } from './routes/docs/voice'
import { Route as DocsUpdatesRouteImport } from './routes/docs/updates'
import { Route as DocsSecurityRouteImport } from './routes/docs/security'
import { Route as DocsConfigurationRouteImport } from './routes/docs/configuration'
import { Route as DocsSkillsRouteImport } from './routes/docs/skills'
import { Route as DocsCliRouteImport } from './routes/docs/cli'
import { Route as DocsBestPracticesRouteImport } from './routes/docs/best-practices'
import { Route as BlogSplatRouteImport } from './routes/blog/$'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OpencodeRoute = OpencodeRouteImport.update({
  id: '/opencode',
  path: '/opencode',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CodexRoute = CodexRouteImport.update({
  id: '/codex',
  path: '/codex',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaudeCodeRoute = ClaudeCodeRouteImport.update({
  id: '/claude-code',
  path: '/claude-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const DocsWorktreesRoute = DocsWorktreesRouteImport.update({
  id: '/worktrees',
  path: '/worktrees',
  getParentRoute: () => DocsRoute,
} as any)
const DocsVoiceRoute = DocsVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => DocsRoute,
} as any)
const DocsUpdatesRoute = DocsUpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSecurityRoute = DocsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DocsRoute,
} as any)
const DocsConfigurationRoute = DocsConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSkillsRoute = DocsSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCliRoute = DocsCliRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => DocsRoute,
} as any)
const DocsBestPracticesRoute = DocsBestPracticesRouteImport.update({
  id: '/best-practices',
  path: '/best-practices',
  getParentRoute: () => DocsRoute,
} as any)
const BlogSplatRoute = BlogSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/claude-code': typeof ClaudeCodeRoute
  '/codex': typeof CodexRoute
  '/docs': typeof DocsRouteWithChildren
  '/download': typeof DownloadRoute
  '/opencode': typeof OpencodeRoute
  '/privacy': typeof PrivacyRoute
  '/blog/$': typeof BlogSplatRoute
  '/docs/best-practices': typeof DocsBestPracticesRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/security': typeof DocsSecurityRoute
  '/docs/skills': typeof DocsSkillsRoute
  '/docs/updates': typeof DocsUpdatesRoute
  '/docs/voice': typeof DocsVoiceRoute
  '/docs/worktrees': typeof DocsWorktreesRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/claude-code': typeof ClaudeCodeRoute
  '/codex': typeof CodexRoute
  '/download': typeof DownloadRoute
  '/opencode': typeof OpencodeRoute
  '/privacy': typeof PrivacyRoute
  '/blog/$': typeof BlogSplatRoute
  '/docs/best-practices': typeof DocsBestPracticesRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/security': typeof DocsSecurityRoute
  '/docs/skills': typeof DocsSkillsRoute
  '/docs/updates': typeof DocsUpdatesRoute
  '/docs/voice': typeof DocsVoiceRoute
  '/docs/worktrees': typeof DocsWorktreesRoute
  '/blog': typeof BlogIndexRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/claude-code': typeof ClaudeCodeRoute
  '/codex': typeof CodexRoute
  '/docs': typeof DocsRouteWithChildren
  '/download': typeof DownloadRoute
  '/opencode': typeof OpencodeRoute
  '/privacy': typeof PrivacyRoute
  '/blog/$': typeof BlogSplatRoute
  '/docs/best-practices': typeof DocsBestPracticesRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/security': typeof DocsSecurityRoute
  '/docs/skills': typeof DocsSkillsRoute
  '/docs/updates': typeof DocsUpdatesRoute
  '/docs/voice': typeof DocsVoiceRoute
  '/docs/worktrees': typeof DocsWorktreesRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/changelog'
    | '/claude-code'
    | '/codex'
    | '/docs'
    | '/download'
    | '/opencode'
    | '/privacy'
    | '/blog/$'
    | '/docs/best-practices'
    | '/docs/cli'
    | '/docs/configuration'
    | '/docs/security'
    | '/docs/skills'
    | '/docs/updates'
    | '/docs/voice'
    | '/docs/worktrees'
    | '/blog/'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/claude-code'
    | '/codex'
    | '/download'
    | '/opencode'
    | '/privacy'
    | '/blog/$'
    | '/docs/best-practices'
    | '/docs/cli'
    | '/docs/configuration'
    | '/docs/security'
    | '/docs/skills'
    | '/docs/updates'
    | '/docs/voice'
    | '/docs/worktrees'
    | '/blog'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/changelog'
    | '/claude-code'
    | '/codex'
    | '/docs'
    | '/download'
    | '/opencode'
    | '/privacy'
    | '/blog/$'
    | '/docs/best-practices'
    | '/docs/cli'
    | '/docs/configuration'
    | '/docs/security'
    | '/docs/skills'
    | '/docs/updates'
    | '/docs/voice'
    | '/docs/worktrees'
    | '/blog/'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  ClaudeCodeRoute: typeof ClaudeCodeRoute
  CodexRoute: typeof CodexRoute
  DocsRoute: typeof DocsRouteWithChildren
  DownloadRoute: typeof DownloadRoute
  OpencodeRoute: typeof OpencodeRoute
  PrivacyRoute: typeof PrivacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opencode': {
      id: '/opencode'
      path: '/opencode'
      fullPath: '/opencode'
      preLoaderRoute: typeof OpencodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codex': {
      id: '/codex'
      path: '/codex'
      fullPath: '/codex'
      preLoaderRoute: typeof CodexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claude-code': {
      id: '/claude-code'
      path: '/claude-code'
      fullPath: '/claude-code'
      preLoaderRoute: typeof ClaudeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/docs/worktrees': {
      id: '/docs/worktrees'
      path: '/worktrees'
      fullPath: '/docs/worktrees'
      preLoaderRoute: typeof DocsWorktreesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/voice': {
      id: '/docs/voice'
      path: '/voice'
      fullPath: '/docs/voice'
      preLoaderRoute: typeof DocsVoiceRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/updates': {
      id: '/docs/updates'
      path: '/updates'
      fullPath: '/docs/updates'
      preLoaderRoute: typeof DocsUpdatesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/security': {
      id: '/docs/security'
      path: '/security'
      fullPath: '/docs/security'
      preLoaderRoute: typeof DocsSecurityRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/configuration': {
      id: '/docs/configuration'
      path: '/configuration'
      fullPath: '/docs/configuration'
      preLoaderRoute: typeof DocsConfigurationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/skills': {
      id: '/docs/skills'
      path: '/skills'
      fullPath: '/docs/skills'
      preLoaderRoute: typeof DocsSkillsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/cli': {
      id: '/docs/cli'
      path: '/cli'
      fullPath: '/docs/cli'
      preLoaderRoute: typeof DocsCliRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/best-practices': {
      id: '/docs/best-practices'
      path: '/best-practices'
      fullPath: '/docs/best-practices'
      preLoaderRoute: typeof DocsBestPracticesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/blog/$': {
      id: '/blog/$'
      path: '/$'
      fullPath: '/blog/$'
      preLoaderRoute: typeof BlogSplatRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSplatRoute: typeof BlogSplatRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSplatRoute: BlogSplatRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DocsRouteChildren {
  DocsBestPracticesRoute: typeof DocsBestPracticesRoute
  DocsCliRoute: typeof DocsCliRoute
  DocsConfigurationRoute: typeof DocsConfigurationRoute
  DocsSecurityRoute: typeof DocsSecurityRoute
  DocsSkillsRoute: typeof DocsSkillsRoute
  DocsUpdatesRoute: typeof DocsUpdatesRoute
  DocsVoiceRoute: typeof DocsVoiceRoute
  DocsWorktreesRoute: typeof DocsWorktreesRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsBestPracticesRoute: DocsBestPracticesRoute,
  DocsCliRoute: DocsCliRoute,
  DocsConfigurationRoute: DocsConfigurationRoute,
  DocsSecurityRoute: DocsSecurityRoute,
  DocsSkillsRoute: DocsSkillsRoute,
  DocsUpdatesRoute: DocsUpdatesRoute,
  DocsVoiceRoute: DocsVoiceRoute,
  DocsWorktreesRoute: DocsWorktreesRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  ClaudeCodeRoute: ClaudeCodeRoute,
  CodexRoute: CodexRoute,
  DocsRoute: DocsRouteWithChildren,
  DownloadRoute: DownloadRoute,
  OpencodeRoute: OpencodeRoute,
  PrivacyRoute: PrivacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
